### ISSUE TITLE
[Problem Installing] : No such file or directory

### ISSUE THREAD

**Issue by ghost** [Pokechu22/ForgeGradle-extensions#1]
Hey,
I'm trying to setup the build environment for WorldDownloader. I've cloned the WorldDownloader repo and the Forge-Gradle-extensions inside the WorldDownloader folder. I'm using the latest gradle docker image.

When I run ./gradlew install inside the ForgeGradle-extensions folder (after making it executable) the following error shows up:
: No such file or directory

What I'm doing wrong?

**Comment by Pokechu22** [comment]
Hm...

```: No such file or directory```

Is that the _entire_ error message (with nothing before it)?  Because that's a really short message and doesn't entirely make sense (`./gradlew` should exist if you're in the right folder)

I'm not entirely sure what would cause it.  You might be able to just not use the gradle wrapper and instead use `gradle install` if you have gradle already installed.  I'll note that I set everything up on windows using Cygwin, so there may be some weirdness due to combined Windows and Linux behaviors from that.

Can you give me more information about your os, please?

**Comment by ghost** [comment]
Yes this is the error message that gradlew give out. I'm using the gradle image from docker and running docker on Linux Mint.

```bash
ghost@Ghoststation ~ $ sudo docker start worlddownloader
worlddownloader
ghost@Ghoststation ~ $ sudo docker attach worlddownloader
root@a64791cef088:/workspace# 
root@a64791cef088:/workspace# ls
1.10		1.11-litemod		README.md     gradlew.bat
1.10-litemod	1.11.2			astyle.cfg    settings.gradle
1.10.2		1.11.2-litemod		build.gradle  share
1.10.2-litemod	ForgeGradle-extensions	gradle	      srgs
1.11		LICENSE.md		gradlew
root@a64791cef088:/workspace# cd ForgeGradle-extensions/
root@a64791cef088:/workspace/ForgeGradle-extensions# ./gradlew install
: No such file or directory
root@a64791cef088:/workspace/ForgeGradle-extensions# ls -la
total 56
drwxr-xr-x  7 root   root   4096 Apr  6 15:56 .
drwxr-xr-x 16 gradle gradle 4096 Apr  6 15:47 ..
drwxr-xr-x  8 root   root   4096 Apr  6 15:47 .git
-rw-r--r--  1 root   root    181 Apr  6 15:47 .gitignore
drwxr-xr-x  4 root   root   4096 Apr  6 15:55 .gradle
-rw-r--r--  1 root   root   1296 Apr  6 15:47 LICENSE.md
-rw-r--r--  1 root   root    454 Apr  6 15:47 README.md
drwxr-xr-x  8 root   root   4096 Apr  6 15:56 build
-rw-r--r--  1 root   root   2777 Apr  6 15:47 build.gradle
drwxr-xr-x  3 root   root   4096 Apr  6 15:47 gradle
-rwxr-xr-x  1 root   root   5131 Apr  6 15:47 gradlew
-rw-r--r--  1 root   root   2404 Apr  6 15:47 gradlew.bat
drwxr-xr-x  3 root   root   4096 Apr  6 15:47 src
root@a64791cef088:/workspace/ForgeGradle-extensions# gradle --version

------------------------------------------------------------
Gradle 3.4.1
------------------------------------------------------------

Build time:   2017-03-03 19:45:41 UTC
Revision:     9eb76efdd3d034dc506c719dac2955efb5ff9a93

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_121 (Oracle Corporation 25.121-b13)
OS:           Linux 4.4.0-72-generic amd64

root@a64791cef088:/workspace/ForgeGradle-extensions# gradle install
Starting a Gradle Daemon (subsequent builds will be faster)
Download http://files.minecraftforge.net/maven/net/minecraftforge/gradle/ForgeGradle/2.2-SNAPSHOT/ForgeGradle-2.2-20170331.025320-32.pom
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-debug-all/5.1/asm-debug-all-5.1.pom
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-parent/5.1/asm-parent-5.1.pom
Download https://repo1.maven.org/maven2/org/ow2/ow2/1.3/ow2-1.3.pom
Download https://repo1.maven.org/maven2/com/google/guava/guava/18.0/guava-18.0.pom
Download https://repo1.maven.org/maven2/com/google/guava/guava-parent/18.0/guava-parent-18.0.pom
Download https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom
Download https://repo1.maven.org/maven2/net/sf/opencsv/opencsv/2.3/opencsv-2.3.pom
Download https://repo1.maven.org/maven2/com/cloudbees/diff4j/1.1/diff4j-1.1.pom
Download https://repo1.maven.org/maven2/com/cloudbees/cloudbees-oss-parent/1/cloudbees-oss-parent-1.pom
Download https://repo1.maven.org/maven2/com/github/abrarsyed/jastyle/jAstyle/1.3/jAstyle-1.3.pom
Download https://repo1.maven.org/maven2/net/sf/trove4j/trove4j/2.1.0/trove4j-2.1.0.pom
Download https://repo1.maven.org/maven2/com/github/jponge/lzma-java/1.3/lzma-java-1.3.pom
Download https://repo1.maven.org/maven2/com/nothome/javaxdelta/2.0.1/javaxdelta-2.0.1.pom
Download https://repo1.maven.org/maven2/com/google/code/gson/gson/2.2.4/gson-2.2.4.pom
Download https://repo1.maven.org/maven2/com/github/tony19/named-regexp/0.2.3/named-regexp-0.2.3.pom
Download http://files.minecraftforge.net/maven/net/minecraftforge/fernflower/2.0-SNAPSHOT/fernflower-2.0-20151214.100946-17.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcomponents-client/4.3.3/httpcomponents-client-4.3.3.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/project/7/project-7.pom
Download https://repo1.maven.org/maven2/org/apache/apache/13/apache-13.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpmime/4.3.3/httpmime-4.3.3.pom
Download https://repo1.maven.org/maven2/org/jvnet/localizer/localizer/1.12/localizer-1.12.pom
Download https://repo1.maven.org/maven2/org/jvnet/localizer/localizer-parent/1.12/localizer-parent-1.12.pom
Download https://repo1.maven.org/maven2/commons-io/commons-io/1.4/commons-io-1.4.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-parent/7/commons-parent-7.pom
Download https://repo1.maven.org/maven2/org/apache/apache/4/apache-4.pom
Download https://repo1.maven.org/maven2/trove/trove/1.0.2/trove-1.0.2.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcomponents-core/4.3.2/httpcomponents-core-4.3.2.pom
Download https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-parent/28/commons-parent-28.pom
Download https://repo1.maven.org/maven2/commons-codec/commons-codec/1.6/commons-codec-1.6.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-parent/22/commons-parent-22.pom
Download https://repo1.maven.org/maven2/org/apache/apache/9/apache-9.pom
Download http://files.minecraftforge.net/maven/net/minecraftforge/gradle/ForgeGradle/2.2-SNAPSHOT/ForgeGradle-2.2-20170331.025320-32.jar
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-debug-all/5.1/asm-debug-all-5.1.jar
Download https://repo1.maven.org/maven2/com/google/guava/guava/18.0/guava-18.0.jar
Download https://repo1.maven.org/maven2/net/sf/opencsv/opencsv/2.3/opencsv-2.3.jar
Download https://repo1.maven.org/maven2/com/cloudbees/diff4j/1.1/diff4j-1.1.jar
Download https://repo1.maven.org/maven2/com/github/abrarsyed/jastyle/jAstyle/1.3/jAstyle-1.3.jar
Download https://repo1.maven.org/maven2/net/sf/trove4j/trove4j/2.1.0/trove4j-2.1.0.jar
Download https://repo1.maven.org/maven2/com/github/jponge/lzma-java/1.3/lzma-java-1.3.jar
Download https://repo1.maven.org/maven2/com/nothome/javaxdelta/2.0.1/javaxdelta-2.0.1.jar
Download https://repo1.maven.org/maven2/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
Download https://repo1.maven.org/maven2/com/github/tony19/named-regexp/0.2.3/named-regexp-0.2.3.jar
Download http://files.minecraftforge.net/maven/net/minecraftforge/fernflower/2.0-SNAPSHOT/fernflower-2.0-20151214.100946-17.jar
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpmime/4.3.3/httpmime-4.3.3.jar
Download https://repo1.maven.org/maven2/org/jvnet/localizer/localizer/1.12/localizer-1.12.jar
Download https://repo1.maven.org/maven2/commons-io/commons-io/1.4/commons-io-1.4.jar
Download https://repo1.maven.org/maven2/trove/trove/1.0.2/trove-1.0.2.jar
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
Download https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
Download https://repo1.maven.org/maven2/commons-codec/commons-codec/1.6/commons-codec-1.6.jar
Generating JAR file 'gradle-api-3.4.1.jar'
:compileJava
Download https://jcenter.bintray.com/commons-io/commons-io/2.5/commons-io-2.5.pom
Download https://jcenter.bintray.com/org/apache/commons/commons-parent/39/commons-parent-39.pom
Download https://jcenter.bintray.com/org/apache/apache/16/apache-16.pom
Download https://jcenter.bintray.com/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.pom
Download http://files.minecraftforge.net/maven/net/minecraftforge/srg2source/Srg2Source/4.0-SNAPSHOT/Srg2Source-4.0-20160818.020434-12.pom
Download https://jcenter.bintray.com/org/eclipse/osgi/3.9.1-v20130814-1242/osgi-3.9.1-v20130814-1242.pom
Download https://jcenter.bintray.com/org/eclipse/equinox/preferences/3.5.100-v20130422-1538/preferences-3.5.100-v20130422-1538.pom
Download https://jcenter.bintray.com/org/eclipse/equinox/common/3.6.200-v20130402-1505/common-3.6.200-v20130402-1505.pom
Download https://jcenter.bintray.com/org/eclipse/core/runtime/3.9.0-v20130326-1255/runtime-3.9.0-v20130326-1255.pom
Download https://jcenter.bintray.com/org/eclipse/text/org.eclipse.text/3.5.101/org.eclipse.text-3.5.101.pom
Download https://jcenter.bintray.com/org/eclipse/core/resources/3.2.1-R32x_v20060914/resources-3.2.1-R32x_v20060914.pom
Download https://jcenter.bintray.com/org/eclipse/core/contenttype/3.4.200-v20130326-1255/contenttype-3.4.200-v20130326-1255.pom
Download https://jcenter.bintray.com/org/ow2/asm/asm-debug-all/5.0.3/asm-debug-all-5.0.3.pom
Download https://jcenter.bintray.com/org/ow2/asm/asm-parent/5.0.3/asm-parent-5.0.3.pom
Download https://jcenter.bintray.com/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.pom
Download https://jcenter.bintray.com/org/eclipse/core/jobs/3.5.300-v20130429-1813/jobs-3.5.300-v20130429-1813.pom
Download http://files.minecraftforge.net/maven/org/eclipse/jdt/org.eclipse.jdt.core/3.12.0.v20160315-2126/org.eclipse.jdt.core-3.12.0.v20160315-2126.pom
Download https://jcenter.bintray.com/fr/inria/gforge/spoon/spoon-core/5.1.0/spoon-core-5.1.0.pom
Download https://jcenter.bintray.com/org/eclipse/osgi/3.10.0-v20140606-1445/osgi-3.10.0-v20140606-1445.pom
Download https://jcenter.bintray.com/org/eclipse/core/jobs/3.6.0-v20140424-0053/jobs-3.6.0-v20140424-0053.pom
Download https://jcenter.bintray.com/org/eclipse/equinox/registry/3.5.400-v20140428-1507/registry-3.5.400-v20140428-1507.pom
Download https://jcenter.bintray.com/org/eclipse/equinox/preferences/3.5.200-v20140224-1527/preferences-3.5.200-v20140224-1527.pom
Download https://jcenter.bintray.com/org/eclipse/core/contenttype/3.4.200-v20140207-1251/contenttype-3.4.200-v20140207-1251.pom
Download https://jcenter.bintray.com/org/eclipse/equinox/app/1.3.200-v20130910-1609/app-1.3.200-v20130910-1609.pom
Download https://jcenter.bintray.com/org/eclipse/core/org.eclipse.core.commands/3.6.0/org.eclipse.core.commands-3.6.0.pom
Download https://jcenter.bintray.com/org/eclipse/equinox/org.eclipse.equinox.common/3.6.0/org.eclipse.equinox.common-3.6.0.pom
Download https://jcenter.bintray.com/org/eclipse/core/runtime/compatibility/3.1.200-v20070502/compatibility-3.1.200-v20070502.pom
Download https://jcenter.bintray.com/org/eclipse/core/expressions/3.3.0-v20070606-0010/expressions-3.3.0-v20070606-0010.pom
Download https://jcenter.bintray.com/org/eclipse/core/filesystem/1.1.0-v20070606/filesystem-1.1.0-v20070606.pom
Download https://jcenter.bintray.com/com/martiansoftware/jsap/2.1/jsap-2.1.pom
Download https://jcenter.bintray.com/log4j/log4j/1.2.17/log4j-1.2.17.pom
Download https://jcenter.bintray.com/org/eclipse/core/runtime/3.10.0-v20140318-2214/runtime-3.10.0-v20140318-2214.pom
Download https://jcenter.bintray.com/org/eclipse/update/configurator/3.2.100-v20070615/configurator-3.2.100-v20070615.pom
Download https://jcenter.bintray.com/commons-io/commons-io/2.5/commons-io-2.5.jar
Download https://jcenter.bintray.com/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.jar
Download http://files.minecraftforge.net/maven/net/minecraftforge/srg2source/Srg2Source/4.0-SNAPSHOT/Srg2Source-4.0-20160818.020434-12.jar
Download https://jcenter.bintray.com/org/eclipse/equinox/common/3.6.200-v20130402-1505/common-3.6.200-v20130402-1505.jar
Download https://jcenter.bintray.com/org/eclipse/text/org.eclipse.text/3.5.101/org.eclipse.text-3.5.101.jar
Download https://jcenter.bintray.com/org/eclipse/core/resources/3.2.1-R32x_v20060914/resources-3.2.1-R32x_v20060914.jar
Download https://jcenter.bintray.com/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
Download http://files.minecraftforge.net/maven/org/eclipse/jdt/org.eclipse.jdt.core/3.12.0.v20160315-2126/org.eclipse.jdt.core-3.12.0.v20160315-2126.jar
Download https://jcenter.bintray.com/fr/inria/gforge/spoon/spoon-core/5.1.0/spoon-core-5.1.0.jar
Download https://jcenter.bintray.com/org/eclipse/equinox/registry/3.5.400-v20140428-1507/registry-3.5.400-v20140428-1507.jar
Download https://jcenter.bintray.com/org/eclipse/equinox/app/1.3.200-v20130910-1609/app-1.3.200-v20130910-1609.jar
Download https://jcenter.bintray.com/org/eclipse/core/org.eclipse.core.commands/3.6.0/org.eclipse.core.commands-3.6.0.jar
Download https://jcenter.bintray.com/org/eclipse/equinox/org.eclipse.equinox.common/3.6.0/org.eclipse.equinox.common-3.6.0.jar
Download https://jcenter.bintray.com/org/eclipse/core/runtime/compatibility/3.1.200-v20070502/compatibility-3.1.200-v20070502.jar
Download https://jcenter.bintray.com/org/eclipse/core/expressions/3.3.0-v20070606-0010/expressions-3.3.0-v20070606-0010.jar
Download https://jcenter.bintray.com/org/eclipse/core/filesystem/1.1.0-v20070606/filesystem-1.1.0-v20070606.jar
Download https://jcenter.bintray.com/com/martiansoftware/jsap/2.1/jsap-2.1.jar
Download https://jcenter.bintray.com/log4j/log4j/1.2.17/log4j-1.2.17.jar
Download https://jcenter.bintray.com/org/eclipse/update/configurator/3.2.100-v20070615/configurator-3.2.100-v20070615.jar
Download https://jcenter.bintray.com/org/eclipse/osgi/3.10.0-v20140606-1445/osgi-3.10.0-v20140606-1445.jar
Download https://jcenter.bintray.com/org/eclipse/core/jobs/3.6.0-v20140424-0053/jobs-3.6.0-v20140424-0053.jar
Download https://jcenter.bintray.com/org/eclipse/equinox/preferences/3.5.200-v20140224-1527/preferences-3.5.200-v20140224-1527.jar
Download https://jcenter.bintray.com/org/eclipse/core/contenttype/3.4.200-v20140207-1251/contenttype-3.4.200-v20140207-1251.jar
Download https://jcenter.bintray.com/org/eclipse/core/runtime/3.10.0-v20140318-2214/runtime-3.10.0-v20140318-2214.jar
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:javadoc UP-TO-DATE
:javadocJar UP-TO-DATE
:install

BUILD SUCCESSFUL

Total time: 48.873 secs
root@a64791cef088:/workspace/ForgeGradle-extensions# cd ..
root@a64791cef088:/workspace# gradlew
bash: gradlew: command not found
root@a64791cef088:/workspace# gradle ^C
root@a64791cef088:/workspace# gradlew :1.11.2-litemod:build
bash: gradlew: command not found
root@a64791cef088:/workspace# gradle :1.11.2-litemod:build
Download http://repo.spongepowered.org/maven/org/spongepowered/mixingradle/0.4-SNAPSHOT/mixingradle-0.4-20160617.140650-4.pom
Download https://repo1.maven.org/maven2/org/eclipse/core/runtime/3.9.0-v20130326-1255/runtime-3.9.0-v20130326-1255.pom
Download http://repo.spongepowered.org/maven/org/spongepowered/mixingradle/0.4-SNAPSHOT/mixingradle-0.4-20160617.140650-4.jar
Download https://repo1.maven.org/maven2/org/eclipse/equinox/common/3.6.200-v20130402-1505/common-3.6.200-v20130402-1505.jar
#################################################
         ForgeGradle 0.0.4-7478651        
  https://github.com/MinecraftForge/ForgeGradle  
#################################################
               Powered by MCP unknown               
             http://modcoderpack.com             
         by: Searge, ProfMobius, Fesh0r,         
         R4wk, ZeuX, IngisKahn, bspkrs           
#################################################
Failed to get version main class
java.lang.RuntimeException: mcVersionJson was null
        at pokechu22.test.begradle.baseedit.BaseEditPlugin.getClientRunClass(BaseEditPlugin.java:220)
        at pokechu22.test.begradle.baseedit.BaseEditPlugin.getClientRunClass(BaseEditPlugin.java:35)
        at net.minecraftforge.gradle.user.UserBasePlugin.afterEvaluate(UserBasePlugin.java:191)
        at net.minecraftforge.gradle.user.UserVanillaBasePlugin.afterEvaluate(UserVanillaBasePlugin.java:96)
        at pokechu22.test.begradle.baseedit.BaseEditPlugin.afterEvaluate(BaseEditPlugin.java:169)
        at net.minecraftforge.gradle.common.BasePlugin$2.execute(BasePlugin.java:201)
        at net.minecraftforge.gradle.common.BasePlugin$2.execute(BasePlugin.java:193)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:93)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:82)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy15.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:82)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:76)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:599)
        at org.gradle.api.internal.project.DefaultProject.evaluationDependsOn(DefaultProject.java:670)
        at org.gradle.api.internal.project.DefaultProject.evaluationDependsOn(DefaultProject.java:662)
        at org.gradle.api.Project$evaluationDependsOn.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at build_2pmiz1w0yz5azu1qqvxdvuqji.run(/workspace/build.gradle:29)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:176)
        at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:181)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:70)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:599)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:125)
        at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:60)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
        at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuildAction.execute(DefaultGradleLauncher.java:233)
        at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuildAction.execute(DefaultGradleLauncher.java:230)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:160)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:31)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
This mapping 'snapshot_20170326' was designed for MC 1.11! Use at your own peril.

FAILURE: Build failed with an exception.

* Where:
Build file '/workspace/1.10.2-litemod/build.gradle' line: 59

* What went wrong:
A problem occurred evaluating project ':1.10.2-litemod'.
> Could not set unknown property 'refMap' for source set 'main' of type org.gradle.api.internal.tasks.DefaultSourceSet.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 16.194 secs
root@a64791cef088:/workspace# 
```

**Comment by ghost** [comment]
I've added my complete command line output in the post above. I tried to build it with Gradle itself, but it seems that it is still missing some API functionality, which if I guess correctly is built via the ForgeGradle extensions. Maybe I need to copy some build output into a plugin folder? I've only worked with Maven before, never with Gradle.

**Comment by Pokechu22** [comment]
Huh, that's very odd - you're running `:1.11.2-litemod:build` but it's running into an error when trying to set up 1.**10**.2.  I think 1.10.2 is one of the first ones that it tries to build, though, so that may make sense.

You shouldn't _need_ to copy anything - using `install` automatically copies the artefact to your local maven repo and other stuff should automatically be downloaded there. 

Note that the huge exception block there regarding failure to find the version JSON is currently normal - it shouldn't interfere with the build right now.  I probably should clean that up later, but it won't block the build (and should go away after a successful build).

`refMap` is provided via [MixinGradle](https://github.com/SpongePowered/MixinGradle), and should still be there...  I don't know why it's complaining about it.  @uyjulian knows mixin better than I do, though.

I'm still not sure why it doesn't accept `./gradlew`.  I've never used gradle through docker before, though (I don't really know anything about docker); I just run it standalone.  So it _might_ be an issue there.

**Comment by uyjulian** [comment]
You need to downgrade Gradle to 2.14.1, otherwise the refMap error will appear...

`: No such file or directory`
Well, isn't that a helpful error message...

**Comment by Pokechu22** [comment]
Fixed by using `ext.refMap` as per SpongePowered/MixinGradle#3.  Gradle 3 and 4 now should be usable with the project (and I've updated the gradle wrapper to use gradle 4)
