### ISSUE TITLE
Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by js802025** [Pokechu22/ForgeGradle-extensions#4]
I get this error when I run ./gradlew install

**Comment by Pokechu22** [comment]
Please run `./gradlew install --info --stacktrace` and post the full output.

**Comment by js802025** [comment]
That just gave me the same error, I tried running gradle install which returned a longer output would u like to see that?

**Comment by Pokechu22** [comment]
Sure.

**Comment by js802025** [comment]
```
Initialized native services in: /Users/jackadee/.gradle/native
The client will now receive all logging from the daemon (pid: 12210). The daemon log file: /Users/jackadee/.gradle/daemon/6.6/daemon-12210.out.log
Starting 7th build in daemon [uptime: 39 mins 59.242 secs, performance: 100%, non-heap usage: 28% of 268.4 MB]
Using 4 worker leases.
Starting Build
Settings evaluated using settings file '/Users/jackadee/Library/CloudStorage/iCloud Drive/python work/github/world_download/ForgeGradle-extensions/settings.gradle'.
Projects loaded. Root project using build file '/Users/jackadee/Library/CloudStorage/iCloud Drive/python work/github/world_download/ForgeGradle-extensions/build.gradle'.
Included projects: [root project 'ForgeGradle-extensions', project ':BEGradle-fg2', project ':BEGradle-fg3', project ':LaunchWrapperTestSuite', project ':share']

> Configure project :
Evaluating root project 'ForgeGradle-extensions' using build file '/Users/jackadee/Library/CloudStorage/iCloud Drive/python work/github/world_download/ForgeGradle-extensions/build.gradle'.

> Configure project :BEGradle-fg2
Evaluating project ':BEGradle-fg2' using build file '/Users/jackadee/Library/CloudStorage/iCloud Drive/python work/github/world_download/ForgeGradle-extensions/BEGradle-fg2/build.gradle'.

> Configure project :BEGradle-fg3
Evaluating project ':BEGradle-fg3' using build file '/Users/jackadee/Library/CloudStorage/iCloud Drive/python work/github/world_download/ForgeGradle-extensions/BEGradle-fg3/build.gradle'.

> Configure project :LaunchWrapperTestSuite
Evaluating project ':LaunchWrapperTestSuite' using build file '/Users/jackadee/Library/CloudStorage/iCloud Drive/python work/github/world_download/ForgeGradle-extensions/LaunchWrapperTestSuite/build.gradle'.

> Configure project :share
Evaluating project ':share' using build file '/Users/jackadee/Library/CloudStorage/iCloud Drive/python work/github/world_download/ForgeGradle-extensions/share/build.gradle'.
All projects evaluated.
Selected primary task 'install' from project :
Tasks to be executed: [task ':BEGradle-fg2:compileJava', task ':BEGradle-fg2:processResources', task ':BEGradle-fg2:classes', task ':BEGradle-fg2:jar', task ':BEGradle-fg2:javadoc', task ':BEGradle-fg2:javadocJar', task ':BEGradle-fg2:install', task ':BEGradle-fg3:compileJava', task ':BEGradle-fg3:processResources', task ':BEGradle-fg3:classes', task ':BEGradle-fg3:jar', task ':BEGradle-fg3:javadoc', task ':BEGradle-fg3:javadocJar', task ':BEGradle-fg3:install', task ':LaunchWrapperTestSuite:compileJava', task ':LaunchWrapperTestSuite:processResources', task ':LaunchWrapperTestSuite:classes', task ':LaunchWrapperTestSuite:jar', task ':LaunchWrapperTestSuite:javadoc', task ':LaunchWrapperTestSuite:javadocJar', task ':LaunchWrapperTestSuite:sourceJar', task ':LaunchWrapperTestSuite:install']
Tasks that were excluded: []
:BEGradle-fg2:compileJava (Thread[Execution worker for ':',5,main]) started.

> Task :BEGradle-fg2:compileJava
Caching disabled for task ':BEGradle-fg2:compileJava' because:
  Build cache is disabled
Task ':BEGradle-fg2:compileJava' is not up-to-date because:
  Task has failed previously.
The input changes require a full rebuild for incremental task ':BEGradle-fg2:compileJava'.
Full recompilation is required because no incremental change information is available. This is usually caused by clean builds or changing compiler arguments.
Compiling with JDK Java compiler API.
/Users/jackadee/Library/CloudStorage/iCloud Drive/python work/github/world_download/ForgeGradle-extensions/share/src/main/java/pokechu22/test/begradle/baseedit/ProcessBasePatchesTask.java:20: error: cannot find symbol
import org.gradle.api.tasks.TaskValidationException;
                           ^
  symbol:   class TaskValidationException
  location: package org.gradle.api.tasks
/Users/jackadee/Library/CloudStorage/iCloud Drive/python work/github/world_download/ForgeGradle-extensions/BEGradle-fg2/src/main/java/pokechu22/test/begradle/baseedit/BaseEditPlugin.java:54: warning: [deprecation] setBaseName(String) in AbstractArchiveTask has been deprecated
                jar.setBaseName(baseName);
                   ^
/Users/jackadee/Library/CloudStorage/iCloud Drive/python work/github/world_download/ForgeGradle-extensions/BEGradle-fg2/src/main/java/pokechu22/test/begradle/baseedit/BaseEditPlugin.java:55: warning: [deprecation] setAppendix(String) in AbstractArchiveTask has been deprecated
                jar.setAppendix("baseedit");
                   ^
/Users/jackadee/Library/CloudStorage/iCloud Drive/python work/github/world_download/ForgeGradle-extensions/BEGradle-fg2/src/main/java/pokechu22/test/begradle/baseedit/BaseEditPlugin.java:56: warning: [deprecation] setExtension(String) in AbstractArchiveTask has been deprecated
                jar.setExtension("zip");
                   ^
/Users/jackadee/Library/CloudStorage/iCloud Drive/python work/github/world_download/ForgeGradle-extensions/BEGradle-fg2/src/main/java/pokechu22/test/begradle/baseedit/BaseEditPlugin.java:71: warning: [deprecation] setBaseName(String) in AbstractArchiveTask has been deprecated
                sourceJar.setBaseName(baseName);
                         ^
/Users/jackadee/Library/CloudStorage/iCloud Drive/python work/github/world_download/ForgeGradle-extensions/BEGradle-fg2/src/main/java/pokechu22/test/begradle/baseedit/BaseEditPlugin.java:171: warning: [deprecation] getArchivePath() in AbstractArchiveTask has been deprecated
                        exec.classpath(jarTask.getArchivePath());
                                              ^
/Users/jackadee/Library/CloudStorage/iCloud Drive/python work/github/world_download/ForgeGradle-extensions/BEGradle-fg2/src/main/java/pokechu22/test/begradle/baseedit/BaseEditPlugin.java:179: warning: [deprecation] getArchivePath() in AbstractArchiveTask has been deprecated
                        exec.classpath(jarTask.getArchivePath());
                                              ^
/Users/jackadee/Library/CloudStorage/iCloud Drive/python work/github/world_download/ForgeGradle-extensions/BEGradle-fg2/src/main/java/pokechu22/test/begradle/baseedit/BaseEditExtension.java:77: warning: [deprecation] getClassifier() in AbstractArchiveTask has been deprecated
                if (Strings.isNullOrEmpty(jar.getClassifier())) {
                                             ^
/Users/jackadee/Library/CloudStorage/iCloud Drive/python work/github/world_download/ForgeGradle-extensions/BEGradle-fg2/src/main/java/pokechu22/test/begradle/baseedit/BaseEditExtension.java:78: warning: [deprecation] setClassifier(String) in AbstractArchiveTask has been deprecated
                        jar.setClassifier("mc" + version);
                           ^
/Users/jackadee/Library/CloudStorage/iCloud Drive/python work/github/world_download/ForgeGradle-extensions/BEGradle-fg2/src/main/java/pokechu22/test/begradle/noinplacereobf/NoInPlaceReobfPlugin.java:41: warning: [deprecation] getDestinationDir() in AbstractArchiveTask has been deprecated
                File originalDirectory = jar.getDestinationDir();
                                            ^
/Users/jackadee/Library/CloudStorage/iCloud Drive/python work/github/world_download/ForgeGradle-extensions/BEGradle-fg2/src/main/java/pokechu22/test/begradle/noinplacereobf/NoInPlaceReobfPlugin.java:42: warning: [deprecation] getArchiveName() in AbstractArchiveTask has been deprecated
                Callable<File> origTarget = () -> new File(originalDirectory, jar.getArchiveName());
                                                                                 ^
/Users/jackadee/Library/CloudStorage/iCloud Drive/python work/github/world_download/ForgeGradle-extensions/BEGradle-fg2/src/main/java/pokechu22/test/begradle/noinplacereobf/NoInPlaceReobfPlugin.java:43: warning: [deprecation] setDestinationDir(File) in AbstractArchiveTask has been deprecated
                jar.setDestinationDir(new File(project.getBuildDir(), "unobfJar"));
                   ^
/Users/jackadee/Library/CloudStorage/iCloud Drive/python work/github/world_download/ForgeGradle-extensions/BEGradle-fg2/src/main/java/pokechu22/test/begradle/noinplacereobf/NoInPlaceReobfPlugin.java:44: warning: [deprecation] getArchivePath() in AbstractArchiveTask has been deprecated
                Callable<File> newTarget = jar::getArchivePath;
                                           ^
/Users/jackadee/Library/CloudStorage/iCloud Drive/python work/github/world_download/ForgeGradle-extensions/share/src/main/java/pokechu22/test/begradle/baseedit/ProcessBasePatchesTask.java:80: error: cannot find symbol
                        throw new TaskValidationException(
                                  ^
  symbol:   class TaskValidationException
  location: class ProcessBasePatchesTask
2 errors
12 warnings

> Task :BEGradle-fg2:compileJava FAILED
:BEGradle-fg2:compileJava (Thread[Execution worker for ':',5,main]) completed. Took 11.414 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':BEGradle-fg2:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':BEGradle-fg2:compileJava'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:208)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:206)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:187)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:57)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:40)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:97)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:51)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:37)
        at org.gradle.api.internal.tasks.compile.AnnotationProcessorDiscoveringCompiler.execute(AnnotationProcessorDiscoveringCompiler.java:51)
        at org.gradle.api.internal.tasks.compile.AnnotationProcessorDiscoveringCompiler.execute(AnnotationProcessorDiscoveringCompiler.java:37)
        at org.gradle.api.internal.tasks.compile.ModuleApplicationNameWritingCompiler.execute(ModuleApplicationNameWritingCompiler.java:46)
        at org.gradle.api.internal.tasks.compile.ModuleApplicationNameWritingCompiler.execute(ModuleApplicationNameWritingCompiler.java:36)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompiler.execute(CleaningJavaCompiler.java:53)
        at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilerFactory.lambda$createRebuildAllCompiler$0(IncrementalCompilerFactory.java:98)
        at org.gradle.api.internal.tasks.compile.incremental.IncrementalResultStoringCompiler.execute(IncrementalResultStoringCompiler.java:60)
        at org.gradle.api.internal.tasks.compile.incremental.IncrementalResultStoringCompiler.execute(IncrementalResultStoringCompiler.java:44)
        at org.gradle.api.internal.tasks.compile.CompileJavaBuildOperationReportingCompiler$2.call(CompileJavaBuildOperationReportingCompiler.java:59)
        at org.gradle.api.internal.tasks.compile.CompileJavaBuildOperationReportingCompiler$2.call(CompileJavaBuildOperationReportingCompiler.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.compile.CompileJavaBuildOperationReportingCompiler.execute(CompileJavaBuildOperationReportingCompiler.java:51)
        at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:293)
        at org.gradle.api.tasks.compile.JavaCompile.performIncrementalCompilation(JavaCompile.java:203)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:183)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.IncrementalInputsTaskAction.doExecute(IncrementalInputsTaskAction.java:32)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
        at org.gradle.api.internal.project.taskfactory.AbstractIncrementalTaskAction.execute(AbstractIncrementalTaskAction.java:25)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:570)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:395)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:387)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:84)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:555)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:538)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:279)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:268)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$0(ExecuteStep.java:32)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:32)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:67)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:36)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:49)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:34)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:43)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:44)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:54)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:38)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:159)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:72)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:43)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:92)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:85)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:94)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:79)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:195)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:187)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)


* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 29s
```

**Comment by Pokechu22** [comment]
You're using Gradle 6.6; this project (and most of the ForgeGradle ecosystem) only works with much older versions (in this case, I target Gradle 4.9).  The Gradle wrapper is supposed to automatically handle that, but it seems like it's not working for you on OSX.

Try running `gradle wrapper --gradle-version 4.9 --distribution-type all` first, and then using the `./gradlew` commands again.

**Comment by js802025** [comment]
same error for the wrapper

**Comment by Pokechu22** [comment]
Can you run `ls -l gradle/wrapper/gradle-wrapper.jar` and `stat gradle/wrapper/gradle-wrapper.jar`, and post the results?

**Comment by js802025** [comment]
-rwxr-xr-x  1 jackadee  staff  59203 Aug 15 14:53 gradle/wrapper/gradle-wrapper.jar

16777220 25478447 -rwxr-xr-x 1 jackadee staff 0 59203 "Aug 15 14:53:44 2020" "Aug 15 14:53:43 2020" "Aug 15 15:11:51 2020" "Aug 15 14:07:13 2020" 4096 120 0x40 gradle/wrapper/gradle-wrapper.jar

**Comment by Pokechu22** [comment]
Hm, that all looks reasonable.  What about `file gradle/wrapper/gradle-wrapper.jar`?

**Comment by js802025** [comment]
gradle/wrapper/gradle-wrapper.jar: Zip archive data, at least v1.0 to extract

**Comment by Pokechu22** [comment]
OK, that should all be correct.  From what I can tell, `gradlew` will give a "Could not find or load main class org.gradle.wrapper.GradleWrapperMain" if it can't load `gradle/wrapper/gradle-wrapper.jar`, though, so *something*'s breaking it and I'm not sure what.  The only thing I can think to suggest is manually installing [Gradle 4.9](https://gradle.org/next-steps/?version=4.9&format=all)...

**Comment by js802025** [comment]
cool, ill try that
